<a href="https://colab.research.google.com/github/RevanthMedukonduru/Pytorch-Learning/blob/main/00_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.3.0+cu121


In [2]:
#scalar
scalar = torch.tensor(7)
print(scalar, scalar.ndim, scalar.item())

#Vector
vector = torch.tensor([7, 7])
print(vector, vector.ndim, vector[0].item())

#MATRIX
MATRIX = torch.tensor([[1, 2, 3],
                        [4, 5, 6],
                        [7, 8, 9]])
print(MATRIX, MATRIX.ndim, MATRIX.shape)

#TENSOR
TENSOR = torch.tensor([[[1, 2, 3],
                        [4, 5, 6],
                        [7, 8, 9]]])
print(TENSOR, TENSOR.ndim, TENSOR.shape)

tensor(7) 0 7
tensor([7, 7]) 1 7
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]) 2 torch.Size([3, 3])
tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]]) 3 torch.Size([1, 3, 3])


In [4]:
# Random Tensor
rand_tensor = torch.rand(3, 4)
rand_tensor, rand_tensor.ndim

(tensor([[0.3234, 0.0914, 0.3085, 0.9876],
         [0.8542, 0.3119, 0.7748, 0.0084],
         [0.2505, 0.9300, 0.9843, 0.9355]]),
 2)

In [7]:
rand_tensor.max(), rand_tensor.min()

(tensor(0.9876), tensor(0.0084))

In [5]:
rand_image_size_tensor = torch.rand(size=(32, 32, 3))
rand_image_size_tensor.ndim, rand_image_size_tensor.shape

(3, torch.Size([32, 32, 3]))

In [8]:
zeroes_tensor = torch.zeros(size=(3, 4))
ones_tensor = torch.ones(size=(3, 4))
zeroes_tensor, ones_tensor

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]))

In [10]:
ones_tensor.dtype

torch.float32

In [16]:
# range of tensors, tensors-like
one_to_ten = torch.arange(start=0, end=11, step=1)
one_to_ten

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [19]:
ten_zeroes = torch.zeros_like(input = one_to_ten)
ten_zeroes

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor Datatypes

In [25]:
float_32_tensor = torch.rand(size=(3, 4), dtype=None, device=None, requires_grad=False)
float_32_tensor, float_32_tensor.dtype, float_32_tensor.requires_grad

(tensor([[0.6929, 0.8835, 0.5062, 0.5639],
         [0.8252, 0.3575, 0.6960, 0.8324],
         [0.8107, 0.6947, 0.7278, 0.7849]]),
 torch.float32,
 False)

In [24]:
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cpu'

In [28]:
int32_tensor = torch.tensor([3, 6, 9], dtype=None)
int32_tensor, int32_tensor.dtype

(tensor([3, 6, 9]), torch.int64)

In [30]:
tensor = torch.tensor([1, 2, 3])
print(tensor+10)
print(tensor*10)
print(tensor-10)
print(tensor/10)

tensor([11, 12, 13])
tensor([10, 20, 30])
tensor([-9, -8, -7])
tensor([0.1000, 0.2000, 0.3000])


In [31]:
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [33]:
torch.matmul(tensor, tensor)

tensor(14)

In [35]:
A=torch.rand(3,2)
B=torch.rand(3,2)
A.shape, B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

In [37]:
torch.matmul(A,B.T)

tensor([[1.0130, 0.3098, 0.9569],
        [0.6239, 0.3439, 0.5286],
        [0.5238, 0.2602, 0.4551]])

In [42]:
tensor = torch.tensor([[1, 2, 3], [4, 5, 6]], dtype=torch.float32)
tensor.min(), tensor.max(), tensor.sum(), tensor.mean()

(tensor(1.), tensor(6.), tensor(21.), tensor(3.5000))

In [45]:
tensor.argmin(), tensor.argmax()

(tensor(0), tensor(5))

In [50]:
a = torch.randn(4, 3)
a, a.ndim

(tensor([[-0.1417,  0.5031,  1.5879],
         [ 0.6637,  0.7413, -1.5078],
         [-0.4315,  0.9886,  0.7847],
         [ 0.7157,  0.0088,  1.2731]]),
 2)

In [49]:
torch.argmax(a, dim=0)

tensor([0, 0, 2, 0])

In [84]:
import torch

x = torch.arange(1, 11)
x, x.shape

(tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]), torch.Size([10]))

In [89]:
x.reshape(1, 10), x.reshape(1, 10).shape

(tensor([[12,  2,  3,  4,  5,  6,  7,  8,  9, 10]]), torch.Size([1, 10]))

In [86]:
h = x.reshape(1, 10)
h

tensor([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

In [87]:
h[:, 0]=12
h

tensor([[12,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

In [88]:
x

tensor([12,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [56]:
x.reshape(10, 1), x.reshape(10, 1).shape

(tensor([[ 1],
         [ 2],
         [ 3],
         [ 4],
         [ 5],
         [ 6],
         [ 7],
         [ 8],
         [ 9],
         [10]]),
 torch.Size([10, 1]))

In [58]:
z = x.view(1, 10)
z, z.shape, x, x.shape

(tensor([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]]),
 torch.Size([1, 10]),
 tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]),
 torch.Size([10]))

In [61]:
z[:, 1] = 5

In [62]:
z, z.shape, x, x.shape

(tensor([[ 1,  5,  3,  4,  5,  6,  7,  8,  9, 10]]),
 torch.Size([1, 10]),
 tensor([ 1,  5,  3,  4,  5,  6,  7,  8,  9, 10]),
 torch.Size([10]))

In [69]:
torch.stack(tensors=(z, x.view(1, 10)), dim=1).shape

torch.Size([1, 2, 10])

In [76]:
z, z.reshape(2, 5)

(tensor([[ 1,  5,  3,  4,  5,  6,  7,  8,  9, 10]]),
 tensor([[ 1,  5,  3,  4,  5],
         [ 6,  7,  8,  9, 10]]))

In [78]:
z=z.reshape(2, 5)

In [80]:
z, z.squeeze(), z.unsqueeze(dim=1)

(tensor([[ 1,  5,  3,  4,  5],
         [ 6,  7,  8,  9, 10]]),
 tensor([[ 1,  5,  3,  4,  5],
         [ 6,  7,  8,  9, 10]]),
 tensor([[[ 1,  5,  3,  4,  5]],
 
         [[ 6,  7,  8,  9, 10]]]))

In [82]:
x = torch.rand(size=(32, 32, 3))
x.permute(dims=(2, 0, 1)).shape

torch.Size([3, 32, 32])

In [83]:
x.shape

torch.Size([32, 32, 3])

In [91]:
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [100]:
x[:, 2, 2]

tensor([9])

In [103]:
import numpy as np

np_arr = np.arange(1,10)
tensor = torch.from_numpy(np_arr)
tensor, tensor.dtype, np_arr, np_arr.dtype

(tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]),
 torch.int64,
 array([1, 2, 3, 4, 5, 6, 7, 8, 9]),
 dtype('int64'))

In [105]:
np_arr = tensor.type(torch.float32).numpy()
tensor, tensor.dtype, np_arr, np_arr.dtype

(tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]),
 torch.int64,
 array([1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=float32),
 dtype('float32'))

In [ ]:
torch.manual_seed(32)

In [2]:
torch.cuda.is_available()

False

In [3]:
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cpu'

In [4]:
torch.cuda.device_count()

0

In [ ]:
tensor_on_gpu.to('cpu').numpy()